config/routes.rb
PracticalApp::Application.routes.draw do

  resources :items do
      post 'sort',on: :collection
  end
end

app/models/item.rb
class Item < ActiveRecord::Base
  attr_accessible :done, :name
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  # GET /items
  # GET /items.json
  def index
    @items = Item.order :position
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @items }
    end
  end

  # GET /items/1
  # GET /items/1.json
  def show
    @item = Item.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @item }
    end
  end

  # GET /items/new
  # GET /items/new.json
  def new
    @item = Item.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @item }
    end
  end

  # GET /items/1/edit
  def edit
    @item = Item.find(params[:id])
  end

  # POST /items
  # POST /items.json
  def create
    @item = Item.new(params[:item])

    respond_to do |format|
      if @item.save
        format.html { redirect_to @item, notice: 'Item was successfully created.' }
        format.json { render json: @item, status: :created, location: @item }
      else
        format.html { render action: "new" }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /items/1
  # PUT /items/1.json
  def update
    @item = Item.find(params[:id])

    respond_to do |format|
      if @item.update_attributes(params[:item])
        format.html { redirect_to @item, notice: 'Item was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /items/1
  # DELETE /items/1.json
  def destroy
    @item = Item.find(params[:id])
    @item.destroy

    respond_to do |format|
      format.html { redirect_to items_url }
      format.json { head :no_content }
    end
  end
  def sort
    @items = Item.all
    @items.each do |item|
      item.position=params['item'].index(item.id.to_s)+1
      item.save
    end
    respond_to do |format|
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/_form.html.slim
= form_for @item do |f|
  - if @item.errors.any?
    #error_explanation
      h2 = "#{pluralize(@item.errors.count, "error")} prohibited this item from being saved:"
      ul
        - @item.errors.full_messages.each do |message|
          li = message

  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :done
    = f.check_box :done
  .actions = f.submit

app/views/items/edit.html.slim
h1 Editing item

== render 'form'

= link_to 'Show', @item
'  |
= link_to 'Back', items_path

app/views/items/index.html.erb
<h1> Listing items </h1>
<table>
  <thead>
  <tr>
    <th> Name</th>
    <th> Done</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>
  </thead>
  <tbody>
  <% @items.each do |item| %>
      <tr id="item_<%= item.id %>">
        <td> <%= item.name %> </td>
        <td> <%= item.done %> </td>
        <td> <%= link_to 'Show', item %> </td>
        <td> <%= link_to 'Edit', edit_item_path(item) %> </td>
        <td> <%= link_to 'Destroy', item, data: { confirm: 'Are you sure?' }, method: :delete %> </td>
      </tr>
  <% end -%>
  </tbody>
  <br>

<%= link_to 'New Item', new_item_path %>

app/views/items/index.html.slim
h1 Listing items

table
  thead
    tr
      th Name
      th Done
      th
      th
      th

  tbody
    - @items.each do |item|
      tr
        td = item.name
        td = item.done
        td = link_to 'Show', item
        td = link_to 'Edit', edit_item_path(item)
        td = link_to 'Destroy', item, data: { confirm: 'Are you sure?' }, method: :delete

br

= link_to 'New Item', new_item_path

div#items-sortable
  - @items.each do |item|
    = div_for item, data: {id: item.id}
      = item.name
      hr

= form_tag do
  = hidden_field_tag :items_ids, ""
  = submit_tag 'Save Changes'

app/views/items/new.html.slim
h1 New item

== render 'form'

= link_to 'Back', items_path

app/views/items/show.html.slim
p#notice = notice

p
  strong Name:
  = @item.name
p
  strong Done:
  = @item.done

= link_to 'Edit', edit_item_path(@item)
'  |
= link_to 'Back', items_path

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>PracticalApp</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>